apiVersion: networking.k8s.io/v1beta1 # extensions/v1beta1
kind: Ingress
metadata:
  name: streamstateingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    cert-manager.io/issuer: "letsencrypt-prod" # "letsencrypt-staging"
    acme.cert-manager.io/http01-edit-in-place: "true"
  labels:
    app: streamstateingress
spec:
  tls: # < placing a host in the TLS config will indicate a certificate should be created
  - hosts:
    - ${organization}.streamstate.org
    secretName: streamstate-internal-cert # < cert-manager will store the created certificate in this secret
  rules:
    - host: ${organization}.streamstate.org
      http:
        paths:
        - path: /ui(/|$)(.*)
          backend:
            serviceName: argo-server
            servicePort: 2747
        - path: /build(/|$)(.*)
          backend:
            serviceName: argowebhook
            servicePort: 12000
        - path: /monitoring(/|$)(.*)
          backend:
            serviceName: prometheus-server 
            servicePort: 9091
        - path: /grafana(/|$)(.*)
          backend:
            serviceName: grafana
            servicePort: 3001