---
## TODO should this be for the entire cluster? 
## or just this organization?
## https://docs.cert-manager.io/en/release-0.11/tasks/issuers/index.html 
## implies that it should be namespaced and per organization
## in which case I should use Issuer rather than ClusterIssuer
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    # The ACME server URL
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: danstahl1138@gmail.com # Update to yours
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-staging
    # Enable the HTTP-01 challenge provider
    solvers:
    - dns01:
        cloudDNS:
          # The ID of the GCP project
          project: {{ .Values.project }} 
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: danstahl1138@gmail.com # Update to yours
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-prod
    # Enable the HTTP-01 challenge provider
    solvers:
    - dns01:
        cloudDNS:
          # The ID of the GCP project
          project: {{ .Values.project }}