apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.dataconfigargo }}
data:
  # property-like keys; each key maps to a simple value
  organization: {{ .Values.organization }}
  project: {{ .Values.project }}
   