apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: streamstateingress
  annotations:
    #kubernetes.io/ingress.global-static-ip-name: ADDRESS_NAME
    #networking.gke.io/managed-certificates: managed-cert
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.regional-static-ip-name: {{ .Values.staticip_name }}
spec:
  rules:
  - http:
      paths:
      - path: /ui/*
        pathType: ImplementationSpecific
        backend:
          service:
            name: streamstate-argo-workflows-server
            port:
              number: 2746
      - path: /monitoring/*
        pathType: ImplementationSpecific
        backend:
          service:
            name: prometheus-operated 
            port:
              number: 9090
      - path: /grafana/*
        pathType: ImplementationSpecific
        backend:
          service:
            name: streamstate-grafana 
            port:
              number: 3000
      - path: /api/replay
        pathType: ImplementationSpecific
        backend:
          service:
            name: argowebhookreplay
            port: 
              number: 12000
      - path: /api/deploy
        pathType: ImplementationSpecific
        backend:
          service:
            name: argowebhookdeploy
            port: 
              number: 13000
      - path: /api/*
        pathType: ImplementationSpecific
        backend:
          service:
            name: restapi
            port:
              number: 8000
      - path: /sparkhistory/*
        pathType: ImplementationSpecific
        backend:
          service: 
            name: streamstate-spark-history-server
            port:
              number: 18080
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: mainui
            port:
              number: 80
      - path: /docs # swagger is hosted at this endpoint
        pathType: ImplementationSpecific
        backend:
          service:
            name: restapi 
            port:
              number: 8000