apiVersion: v1
kind: Secret
metadata:
  name: oauth2-proxy-config
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: cookie-secret
data: 
  client-id: {{ .Values.oauth.client_id }} 
  client-secret: {{ .Values.oauth.client_secret }}
  oidc-issuer-url: {{ .Values.oauth.base_64_oidc_issuer_url }} 
  extra-jwt-issuers: {{ .Values.oauth.base_64_extra_jwt_issuers }} 