---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  namespace: {{ .Values.namespace.controlpanenamespace }}
  labels:
    app: prometheus-operator
    release: prometheus
  name: spark-monitor
spec:
  podMetricsEndpoints:
    - interval: 5s
      port: spark-ui
      scheme: http
      path: /metrics/prometheus
    - interval: 5s
      port: spark-ui
      scheme: http
      path: /metrics/executors/prometheus
  namespaceSelector:
    matchNames:
      - {{ .Values.namespace.sparknamespace }}
  selector:
    matchLabels:
      metrics-exposed: "true"