{{- range $k, $v := .Values.serviceaccounts }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $v.name }}
  {{ if $v.namespace }}
  namespace: {{ $v.namespace }}
  {{ end }}
  {{ if $v.iam_binding }}
  annotations:
    iam.gke.io/gcp-service-account: {{ $v.iam_binding }}
  {{ end }}
---
{{- end }}