service:
  type: NodePort
  port: 3001
  targetPort: 3001

# https://grafana.com/tutorials/run-grafana-behind-a-proxy/
# gateway/ingress.yml
grafana.ini:
  server:
    domain: ${organization}.streamstate.org 
    root_url: https://${organization}.streamstate.org/grafana/
    serve_from_sub_path: true
  auth:
    anonymous:
      enabled: true
extraContainers: |
  - name: reverseproxy
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.1.3
    ports:
    - containerPort: 3001
      name: web
    readinessProbe:
      httpGet:
        path: /ping
        port: 3001
        scheme: HTTP
      initialDelaySeconds: 10
      periodSeconds: 20
    args:
      - --provider=oidc
      - --oidc-issuer-url=https://dev-20490044.okta.com/oauth2/default
      - --reverse-proxy=true
      - --upstream=http://localhost:3000 
      - --pass-access-token=true
      - --email-domain=*
      - --skip-provider-button=true
      - --http-address=0.0.0.0:3001
      - --redirect-url=https://${organization}.streamstate.org/grafana/oauth2/callback
      - --pass-host-header
      - --exclude-logging-path=/ping
    env:
    - name: OAUTH2_PROXY_CLIENT_ID
      valueFrom:
        secretKeyRef:
          name: oauth2-proxy-config
          key: client-id
      # value: <Client ID>
    - name: OAUTH2_PROXY_CLIENT_SECRET
      valueFrom:
        secretKeyRef:
          name: oauth2-proxy-config
          key: client-secret
    - name: OAUTH2_PROXY_COOKIE_SECRET
      valueFrom:
        secretKeyRef:
          name: oauth2-proxy-config
          key: cookie-secret
rbac:
  namespaced: true