name: test_code
on: [push]
jobs:
  run_helm_lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Test chart
      run: |
        cd streamstate
        helm lint .
        helm dependency build
        helm template .